### ISSUE TITLE
stream demo doesn't show result !!

### ISSUE THREAD

**Issue by mikakhaled** [EddieLa/JOB#27]
seems like the callback is not responding at all .
just tried that in streamdemo.html 
JOB.StreamCallback = function(result) {
                console.log('test call back ')
                if(result.length > 0){
                    var tempArray = [];
                    for(var i = 0; i < result.length; i++) {
                        tempArray.push(result[i].Format+" : "+result[i].Value);
                    }
                    Result.innerHTML=tempArray.join("<br />");
                }
            };
but the console didnt log any thing

**Comment by CDIDEV** [comment]
I'm having the same issue. My StreamCallback is never called. Any tips?
