### ISSUE TITLE
Uncaught TypeError: Cannot set property 'width' of null

### ISSUE THREAD

**Issue by igorissen** [EddieLa/JOB#30]
Hi,

I just found your library and when I try to test it with an image I got the error in the subject. I want to add it in my AngularJS application.

```javascript
function setFiles(element) {
  var showPicture = document.createElement("img");

  console.log(element.files);

  var URL = window.URL || window.webkitURL;
  showPicture.onload = function (event) {
    JOB.DecodeImage(showPicture);
    URL.revokeObjectURL(showPicture.src);
  };

  showPicture.src = URL.createObjectURL(element.files[ 0 ]);
}

JOB.SetImageCallback(function (result) { console.log(result); });
```

Any idea ?

Thanks.

**Comment by KubaZ** [comment]
I think u should first append showPicture element to document, then set its src attribute. Otherwise the img node wont be attached to document, so it wont be rendered and u wont get its 'width' property.

**Comment by igorissen** [comment]
I found my mistake. I'm calling `JOB.init();` instead of `JOB.Init();`. Now my code is working great.

Thanks for your work.
