### ISSUE TITLE
IE9 is not working...

### ISSUE THREAD

**Issue by Hoooooni** [EddieLa/JOB#34]
IE 9 is not supported webwork....

help me plz...

**Comment by EddieLa** [comment]
Hi,

The fact that internet explorer doesn't support webworkers isn't really something I can help with, I would suggest complaining to microsoft.

**Comment by Hoooooni** [comment]
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT

**Comment by hkliya** [comment]
My experience is take a picture and upload it to the backend, parse the picture with Zxing. It worked for me.
